services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cyber}
      POSTGRES_USER: ${POSTGRES_USER:-cyber_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cyber_pass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  etl:
    build:
      context: .
      dockerfile: ops/Dockerfile.etl
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./data:/mnt/data

  app:
    build:
      context: .
      dockerfile: ops/Dockerfile.app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - ./models:/models


  models:
    image: python:3.11-slim
    working_dir: /models
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./models:/models
    command: ["bash", "-lc", "pip install -r requirements.txt && python train_high_impact.py"]

volumes:
  pgdata:
